nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.12.0.cjs

npmRegistryServer: "https://registry.npmjs.org"

npmRegistries:
  "https://registry.npmjs.org":
    npmAuthToken: "${NPM_AUTH_TOKEN:-}"
